name: Build Example Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Android build
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Build Android APK
        run: |
          cd example
          flutter build apk --release --no-tree-shake-icons

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: example/build/app/outputs/flutter-apk/app-release.apk

  # Linux build
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Build Linux
        run: |
          cd example
          flutter build linux --release

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: example/build/linux/x64/release/bundle/

  # Windows build
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Build Windows
        run: |
          cd example
          flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: example/build/windows/x64/runner/Release/

  # macOS build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Build macOS
        run: |
          cd example
          flutter build macos --release

      - name: Create macOS ZIP
        run: |
          cd example/build/macos/Build/Products/Release
          ditto -c -k --keepParent "ente_directory_picker_example.app" "ente_directory_picker_example.zip"

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: example/build/macos/Build/Products/Release/ente_directory_picker_example.zip

  # Create release with artifacts
  release:
    needs: [build-android, build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release packages
        run: |
          # Rename Android APK
          mv android-apk/app-release.apk ente-directory-picker-example.apk

          # Package Linux build
          cd linux-build && tar czf ../ente-directory-picker-example-linux.tar.gz * && cd ..

          # Package Windows build
          cd windows-build && zip -r ../ente-directory-picker-example-windows.zip * && cd ..

          # Move macOS build
          mv macos-build/ente_directory_picker_example.zip ente-directory-picker-example-macos.zip

      - name: Get commit info
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ steps.commit.outputs.date }}-${{ steps.commit.outputs.sha_short }}
          name: Dev Build ${{ steps.commit.outputs.date }}
          body: |
            Development build from commit ${{ github.sha }}

            ### Downloads
            - **Android:** ente-directory-picker-example.apk
            - **Linux:** ente-directory-picker-example-linux.tar.gz
            - **Windows:** ente-directory-picker-example-windows.zip
            - **macOS:** ente-directory-picker-example-macos.zip
          files: |
            ente-directory-picker-example.apk
            ente-directory-picker-example-linux.tar.gz
            ente-directory-picker-example-windows.zip
            ente-directory-picker-example-macos.zip
          draft: false
          prerelease: true